name: mdl
description: Material Design Lite for Dart
version: 2.1.4
author: Mike Mitterer <office@mikemitterer.at>
homepage: http://www.material-design-lite.pub

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  browser: ^0.10.0

  intl: ^0.15.0
  validate: ^1.0.0
  browser_detect: ^1.0.0

  logging: ^0.11.0
  logging_handlers: ^0.8.0
  console_log_handler: ^0.2.0
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  route_hierarchical: ^0.7.0

  mustache: ^0.2.0
    #git: git://github.com/xxgreg/mustache

  dnd: ^0.3.0

  dice: ^1.7.0
    # path: /Volumes/Daten/DevLocal/DevDart/dice
    
  barback: ^0.15.0

  path: ^1.4.0

  l10n: ^1.0.0
    # path: /Volumes/Daten/DevLocal/DevDart/L10N4Dart

dev_dependencies:
  test: any
  args: any
  material_icons: any
  grinder: any
  mdl_grinder:
    git: https://github.com/MikeMitterer/dart-mdl-grinder
    # path: /Volumes/Daten/DevLocal/DevDart/MaterialGrinder

transformers:
#  - di
  - mdl

  - $dart2js:
      commandLineOptions: [--enable-experimental-mirrors]


